### ISSUE TITLE
save-images.sh 관련

### ISSUE THREAD

**Issue by shouts77** [johngrib/johngrib-jekyll-skeleton#47]
안녕하세요. 우선 이미지 경로를 안정적으로 유지할 수 있도록 업데이트 해주신 부분에 대해 감사드립니다. 지금 등록하는 글은 이슈로 제출해야 하는지 조금 고민이 되긴 했습니다. 이번 업데이트와 맞물려서 위키 파일 템플릿 12행에 'resource'가 추가되었는데, save-images.sh 스크립트에서 'RESOURCE_DIR'을 가져올 때 head로 10줄(default)만 가져오다 보니 경로가 의도대로 만들어지지 않았습니다.
```
RESOURCE_DIR=`head $CHANGED_FILE | egrep -o '[A-F0-9-]{2}/[A-F0-9-]{34}$'`
```
(이는 템플릿의 'resource' 행 위치를 변경하거나 head 명령어에 -12 옵션만 주면 금방 해결 될 수 있습니다. 아마도 기존 파일에 uuid를 추가하실 때 행 위치는 8번째였는데, 템플릿으로 정리하실 때는 제일 아래가 적당해 보이셔서 마지막행(12행) 위치로 변경하셨던 것 같습니다.)

그리고 초보자로서 궁금한 점도 있습니다. set-vimwiki.vim 의 템플릿에서 uuid 만드실 때  substitute(system("uuidgen"), '\n', '', '')) 이렇게 하면 앞의 두 자리가 '/'로 구분되지 않는데, 이는 어떻게 처리하시는지 궁금합니다.

내년에는 더 건강해지신 John Grib님을 트위터에서 만나보게 되었으면 좋겠습니다.
항상 감사드립니다.

**Comment by johngrib** [comment]
아, resource 메타데이터 위치랑 `/` 집어넣는 건 제 로컬 컴퓨터에서는 작업을 해놨는데 아직 커밋을 안 하고 있었습니다. 방금 올렸으니 확인해보세요.
https://github.com/johngrib/dotfiles/commit/5f9b62dbc5104993d611be689d0460b09ac9d4c8

건강을 걱정해주셔서 감사합니다 @shouts77 님!

**Comment by johngrib** [comment]
아참, UUID를 변형한 리소스 경로를 사용하고 계신다면 제가 관리하고 있는 vimwiki를 참고해보시면 도움이 될 거에요. UUID 변형 리소스에서 엔터를 입력하면 해당 경로나 이미지 등을 vim 바깥에서 열어줍니다.

https://github.com/johngrib/vimwiki/blob/johngrib/autoload/vimwiki/base.vim#L1640-L1661

**Comment by shouts77** [comment]
추가로 참고할 내용까지 알려주셔서 감사합니다. 꼭 살펴보겠습니다.
